version: '3.8'

services:

  api:
    build: .
    environment:
      - PORT=${PORT}
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=${DB_NAME}
      - REDIS_URI=redis
      - SECRET=${SECRET}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
      - redis
      
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:6.2.7
    ports: 
      - 6379:6379
    volumes:
      - redisdb:/data 

volumes:
  mongodb:
  redisdb: